/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void buttonLos_click(GButton source, GEvent event) { //_CODE_:buttonLos:714971:
  labelResult.setText(verarbeite(textarea.getText()));
} //_CODE_:buttonLos:714971:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("Arial", G4P.PLAIN, 16);
  G4P.setInputFont("Arial", G4P.BOLD, 16);
  surface.setTitle("Textfeld Vorlage");
  textarea = new GTextArea(this, 10, 10, 380, 130, G4P.SCROLLBARS_NONE);
  textarea.setOpaque(true);
  buttonLos = new GButton(this, 280, 150, 110, 30);
  buttonLos.setText("Start");
  buttonLos.addEventHandler(this, "buttonLos_click");
  labelResult = new GLabel(this, 10, 150, 260, 140);
  labelResult.setTextAlign(GAlign.LEFT, GAlign.TOP);
  labelResult.setText(" ");
  labelResult.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GTextArea textarea; 
GButton buttonLos; 
GLabel labelResult; 
